<?php
/**
 * AsnInfo
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  WhoisFreaks
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * WhoisFreaks API
 *
 * Complete WhoisFreaks API — WHOIS, DNS, SSL, Geolocation, Typosquatting, IP Intelligence, Domain Reputation, and bulk database downloads.  ## Authentication All requests require an `apiKey` query parameter.  ## Resources - Docs: https://whoisfreaks.com/documentation - Billing: https://billing.whoisfreaks.com - Support: support@whoisfreaks.com
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@whoisfreaks.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace WhoisFreaks\Model;

use \ArrayAccess;
use \WhoisFreaks\ObjectSerializer;

/**
 * AsnInfo Class Doc Comment
 *
 * @category Class
 * @package  WhoisFreaks
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AsnInfo implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AsnInfo';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'asNumber' => 'string',
        'organization' => 'string',
        'country' => 'string',
        'type' => 'string',
        'domain' => 'string',
        'dateAllocated' => 'string',
        'asnName' => 'string',
        'allocationStatus' => 'string',
        'numOfIpv4Routes' => 'string',
        'numOfIpv6Routes' => 'string',
        'rir' => 'string',
        'routes' => 'string[]',
        'downstreams' => '\WhoisFreaks\Model\AsnPeer[]',
        'upstreams' => '\WhoisFreaks\Model\AsnPeer[]',
        'peers' => '\WhoisFreaks\Model\AsnPeer[]',
        'whoisResponse' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'asNumber' => null,
        'organization' => null,
        'country' => null,
        'type' => null,
        'domain' => null,
        'dateAllocated' => null,
        'asnName' => null,
        'allocationStatus' => null,
        'numOfIpv4Routes' => null,
        'numOfIpv6Routes' => null,
        'rir' => null,
        'routes' => null,
        'downstreams' => null,
        'upstreams' => null,
        'peers' => null,
        'whoisResponse' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'asNumber' => false,
        'organization' => false,
        'country' => false,
        'type' => false,
        'domain' => false,
        'dateAllocated' => false,
        'asnName' => false,
        'allocationStatus' => false,
        'numOfIpv4Routes' => false,
        'numOfIpv6Routes' => false,
        'rir' => false,
        'routes' => false,
        'downstreams' => false,
        'upstreams' => false,
        'peers' => false,
        'whoisResponse' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'asNumber' => 'as_number',
        'organization' => 'organization',
        'country' => 'country',
        'type' => 'type',
        'domain' => 'domain',
        'dateAllocated' => 'date_allocated',
        'asnName' => 'asn_name',
        'allocationStatus' => 'allocation_status',
        'numOfIpv4Routes' => 'num_of_ipv4_routes',
        'numOfIpv6Routes' => 'num_of_ipv6_routes',
        'rir' => 'rir',
        'routes' => 'routes',
        'downstreams' => 'downstreams',
        'upstreams' => 'upstreams',
        'peers' => 'peers',
        'whoisResponse' => 'whois_response'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'asNumber' => 'setAsNumber',
        'organization' => 'setOrganization',
        'country' => 'setCountry',
        'type' => 'setType',
        'domain' => 'setDomain',
        'dateAllocated' => 'setDateAllocated',
        'asnName' => 'setAsnName',
        'allocationStatus' => 'setAllocationStatus',
        'numOfIpv4Routes' => 'setNumOfIpv4Routes',
        'numOfIpv6Routes' => 'setNumOfIpv6Routes',
        'rir' => 'setRir',
        'routes' => 'setRoutes',
        'downstreams' => 'setDownstreams',
        'upstreams' => 'setUpstreams',
        'peers' => 'setPeers',
        'whoisResponse' => 'setWhoisResponse'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'asNumber' => 'getAsNumber',
        'organization' => 'getOrganization',
        'country' => 'getCountry',
        'type' => 'getType',
        'domain' => 'getDomain',
        'dateAllocated' => 'getDateAllocated',
        'asnName' => 'getAsnName',
        'allocationStatus' => 'getAllocationStatus',
        'numOfIpv4Routes' => 'getNumOfIpv4Routes',
        'numOfIpv6Routes' => 'getNumOfIpv6Routes',
        'rir' => 'getRir',
        'routes' => 'getRoutes',
        'downstreams' => 'getDownstreams',
        'upstreams' => 'getUpstreams',
        'peers' => 'getPeers',
        'whoisResponse' => 'getWhoisResponse'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('asNumber', $data ?? [], null);
        $this->setIfExists('organization', $data ?? [], null);
        $this->setIfExists('country', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('domain', $data ?? [], null);
        $this->setIfExists('dateAllocated', $data ?? [], null);
        $this->setIfExists('asnName', $data ?? [], null);
        $this->setIfExists('allocationStatus', $data ?? [], null);
        $this->setIfExists('numOfIpv4Routes', $data ?? [], null);
        $this->setIfExists('numOfIpv6Routes', $data ?? [], null);
        $this->setIfExists('rir', $data ?? [], null);
        $this->setIfExists('routes', $data ?? [], null);
        $this->setIfExists('downstreams', $data ?? [], null);
        $this->setIfExists('upstreams', $data ?? [], null);
        $this->setIfExists('peers', $data ?? [], null);
        $this->setIfExists('whoisResponse', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets asNumber
     *
     * @return string|null
     */
    public function getAsNumber()
    {
        return $this->container['asNumber'];
    }

    /**
     * Sets asNumber
     *
     * @param string|null $asNumber asNumber
     *
     * @return self
     */
    public function setAsNumber($asNumber)
    {
        if (is_null($asNumber)) {
            throw new \InvalidArgumentException('non-nullable asNumber cannot be null');
        }
        $this->container['asNumber'] = $asNumber;

        return $this;
    }

    /**
     * Gets organization
     *
     * @return string|null
     */
    public function getOrganization()
    {
        return $this->container['organization'];
    }

    /**
     * Sets organization
     *
     * @param string|null $organization organization
     *
     * @return self
     */
    public function setOrganization($organization)
    {
        if (is_null($organization)) {
            throw new \InvalidArgumentException('non-nullable organization cannot be null');
        }
        $this->container['organization'] = $organization;

        return $this;
    }

    /**
     * Gets country
     *
     * @return string|null
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param string|null $country country
     *
     * @return self
     */
    public function setCountry($country)
    {
        if (is_null($country)) {
            throw new \InvalidArgumentException('non-nullable country cannot be null');
        }
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string|null $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets domain
     *
     * @return string|null
     */
    public function getDomain()
    {
        return $this->container['domain'];
    }

    /**
     * Sets domain
     *
     * @param string|null $domain domain
     *
     * @return self
     */
    public function setDomain($domain)
    {
        if (is_null($domain)) {
            throw new \InvalidArgumentException('non-nullable domain cannot be null');
        }
        $this->container['domain'] = $domain;

        return $this;
    }

    /**
     * Gets dateAllocated
     *
     * @return string|null
     */
    public function getDateAllocated()
    {
        return $this->container['dateAllocated'];
    }

    /**
     * Sets dateAllocated
     *
     * @param string|null $dateAllocated dateAllocated
     *
     * @return self
     */
    public function setDateAllocated($dateAllocated)
    {
        if (is_null($dateAllocated)) {
            throw new \InvalidArgumentException('non-nullable dateAllocated cannot be null');
        }
        $this->container['dateAllocated'] = $dateAllocated;

        return $this;
    }

    /**
     * Gets asnName
     *
     * @return string|null
     */
    public function getAsnName()
    {
        return $this->container['asnName'];
    }

    /**
     * Sets asnName
     *
     * @param string|null $asnName asnName
     *
     * @return self
     */
    public function setAsnName($asnName)
    {
        if (is_null($asnName)) {
            throw new \InvalidArgumentException('non-nullable asnName cannot be null');
        }
        $this->container['asnName'] = $asnName;

        return $this;
    }

    /**
     * Gets allocationStatus
     *
     * @return string|null
     */
    public function getAllocationStatus()
    {
        return $this->container['allocationStatus'];
    }

    /**
     * Sets allocationStatus
     *
     * @param string|null $allocationStatus allocationStatus
     *
     * @return self
     */
    public function setAllocationStatus($allocationStatus)
    {
        if (is_null($allocationStatus)) {
            throw new \InvalidArgumentException('non-nullable allocationStatus cannot be null');
        }
        $this->container['allocationStatus'] = $allocationStatus;

        return $this;
    }

    /**
     * Gets numOfIpv4Routes
     *
     * @return string|null
     */
    public function getNumOfIpv4Routes()
    {
        return $this->container['numOfIpv4Routes'];
    }

    /**
     * Sets numOfIpv4Routes
     *
     * @param string|null $numOfIpv4Routes numOfIpv4Routes
     *
     * @return self
     */
    public function setNumOfIpv4Routes($numOfIpv4Routes)
    {
        if (is_null($numOfIpv4Routes)) {
            throw new \InvalidArgumentException('non-nullable numOfIpv4Routes cannot be null');
        }
        $this->container['numOfIpv4Routes'] = $numOfIpv4Routes;

        return $this;
    }

    /**
     * Gets numOfIpv6Routes
     *
     * @return string|null
     */
    public function getNumOfIpv6Routes()
    {
        return $this->container['numOfIpv6Routes'];
    }

    /**
     * Sets numOfIpv6Routes
     *
     * @param string|null $numOfIpv6Routes numOfIpv6Routes
     *
     * @return self
     */
    public function setNumOfIpv6Routes($numOfIpv6Routes)
    {
        if (is_null($numOfIpv6Routes)) {
            throw new \InvalidArgumentException('non-nullable numOfIpv6Routes cannot be null');
        }
        $this->container['numOfIpv6Routes'] = $numOfIpv6Routes;

        return $this;
    }

    /**
     * Gets rir
     *
     * @return string|null
     */
    public function getRir()
    {
        return $this->container['rir'];
    }

    /**
     * Sets rir
     *
     * @param string|null $rir rir
     *
     * @return self
     */
    public function setRir($rir)
    {
        if (is_null($rir)) {
            throw new \InvalidArgumentException('non-nullable rir cannot be null');
        }
        $this->container['rir'] = $rir;

        return $this;
    }

    /**
     * Gets routes
     *
     * @return string[]|null
     */
    public function getRoutes()
    {
        return $this->container['routes'];
    }

    /**
     * Sets routes
     *
     * @param string[]|null $routes routes
     *
     * @return self
     */
    public function setRoutes($routes)
    {
        if (is_null($routes)) {
            throw new \InvalidArgumentException('non-nullable routes cannot be null');
        }
        $this->container['routes'] = $routes;

        return $this;
    }

    /**
     * Gets downstreams
     *
     * @return \WhoisFreaks\Model\AsnPeer[]|null
     */
    public function getDownstreams()
    {
        return $this->container['downstreams'];
    }

    /**
     * Sets downstreams
     *
     * @param \WhoisFreaks\Model\AsnPeer[]|null $downstreams downstreams
     *
     * @return self
     */
    public function setDownstreams($downstreams)
    {
        if (is_null($downstreams)) {
            throw new \InvalidArgumentException('non-nullable downstreams cannot be null');
        }
        $this->container['downstreams'] = $downstreams;

        return $this;
    }

    /**
     * Gets upstreams
     *
     * @return \WhoisFreaks\Model\AsnPeer[]|null
     */
    public function getUpstreams()
    {
        return $this->container['upstreams'];
    }

    /**
     * Sets upstreams
     *
     * @param \WhoisFreaks\Model\AsnPeer[]|null $upstreams upstreams
     *
     * @return self
     */
    public function setUpstreams($upstreams)
    {
        if (is_null($upstreams)) {
            throw new \InvalidArgumentException('non-nullable upstreams cannot be null');
        }
        $this->container['upstreams'] = $upstreams;

        return $this;
    }

    /**
     * Gets peers
     *
     * @return \WhoisFreaks\Model\AsnPeer[]|null
     */
    public function getPeers()
    {
        return $this->container['peers'];
    }

    /**
     * Sets peers
     *
     * @param \WhoisFreaks\Model\AsnPeer[]|null $peers peers
     *
     * @return self
     */
    public function setPeers($peers)
    {
        if (is_null($peers)) {
            throw new \InvalidArgumentException('non-nullable peers cannot be null');
        }
        $this->container['peers'] = $peers;

        return $this;
    }

    /**
     * Gets whoisResponse
     *
     * @return string|null
     */
    public function getWhoisResponse()
    {
        return $this->container['whoisResponse'];
    }

    /**
     * Sets whoisResponse
     *
     * @param string|null $whoisResponse whoisResponse
     *
     * @return self
     */
    public function setWhoisResponse($whoisResponse)
    {
        if (is_null($whoisResponse)) {
            throw new \InvalidArgumentException('non-nullable whoisResponse cannot be null');
        }
        $this->container['whoisResponse'] = $whoisResponse;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


