<?php
/**
 * InetNum
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  WhoisFreaks
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * WhoisFreaks API
 *
 * Complete WhoisFreaks API — WHOIS, DNS, SSL, Geolocation, Typosquatting, IP Intelligence, Domain Reputation, and bulk database downloads.  ## Authentication All requests require an `apiKey` query parameter.  ## Resources - Docs: https://whoisfreaks.com/documentation - Billing: https://billing.whoisfreaks.com - Support: support@whoisfreaks.com
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@whoisfreaks.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace WhoisFreaks\Model;

use \ArrayAccess;
use \WhoisFreaks\ObjectSerializer;

/**
 * InetNum Class Doc Comment
 *
 * @category Class
 * @package  WhoisFreaks
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class InetNum implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'InetNum';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'startIp' => 'string',
        'endIp' => 'string',
        'cidr' => 'string[]',
        'netName' => 'string',
        'netHandle' => 'string',
        'description' => 'string[]',
        'countries' => 'string[]',
        'geofeed' => 'string',
        'latitude' => 'float',
        'longitude' => 'float',
        'city' => 'string',
        'languages' => 'string[]',
        'status' => 'string',
        'organization' => 'string',
        'sponsoringOrganization' => 'string',
        'remarks' => 'string[]',
        'assignmentSize' => 'string',
        'notify' => 'string[]',
        'mntBy' => 'string[]',
        'mntLower' => 'string[]',
        'mntDomains' => 'string[]',
        'mntRoutes' => 'string[]',
        'mntIrt' => 'string[]',
        'dateCreated' => 'string',
        'dateUpdated' => 'string',
        'source' => 'string',
        'parents' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'startIp' => null,
        'endIp' => null,
        'cidr' => null,
        'netName' => null,
        'netHandle' => null,
        'description' => null,
        'countries' => null,
        'geofeed' => null,
        'latitude' => null,
        'longitude' => null,
        'city' => null,
        'languages' => null,
        'status' => null,
        'organization' => null,
        'sponsoringOrganization' => null,
        'remarks' => null,
        'assignmentSize' => null,
        'notify' => null,
        'mntBy' => null,
        'mntLower' => null,
        'mntDomains' => null,
        'mntRoutes' => null,
        'mntIrt' => null,
        'dateCreated' => null,
        'dateUpdated' => null,
        'source' => null,
        'parents' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'startIp' => false,
        'endIp' => false,
        'cidr' => false,
        'netName' => false,
        'netHandle' => false,
        'description' => false,
        'countries' => false,
        'geofeed' => false,
        'latitude' => false,
        'longitude' => false,
        'city' => false,
        'languages' => false,
        'status' => false,
        'organization' => false,
        'sponsoringOrganization' => false,
        'remarks' => false,
        'assignmentSize' => false,
        'notify' => false,
        'mntBy' => false,
        'mntLower' => false,
        'mntDomains' => false,
        'mntRoutes' => false,
        'mntIrt' => false,
        'dateCreated' => false,
        'dateUpdated' => false,
        'source' => false,
        'parents' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'startIp' => 'start_ip',
        'endIp' => 'end_ip',
        'cidr' => 'cidr',
        'netName' => 'net_name',
        'netHandle' => 'net_handle',
        'description' => 'description',
        'countries' => 'countries',
        'geofeed' => 'geofeed',
        'latitude' => 'latitude',
        'longitude' => 'longitude',
        'city' => 'city',
        'languages' => 'languages',
        'status' => 'status',
        'organization' => 'organization',
        'sponsoringOrganization' => 'sponsoring_organization',
        'remarks' => 'remarks',
        'assignmentSize' => 'assignment_size',
        'notify' => 'notify',
        'mntBy' => 'mnt_by',
        'mntLower' => 'mnt_lower',
        'mntDomains' => 'mnt_domains',
        'mntRoutes' => 'mnt_routes',
        'mntIrt' => 'mnt_irt',
        'dateCreated' => 'date_created',
        'dateUpdated' => 'date_updated',
        'source' => 'source',
        'parents' => 'parents'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'startIp' => 'setStartIp',
        'endIp' => 'setEndIp',
        'cidr' => 'setCidr',
        'netName' => 'setNetName',
        'netHandle' => 'setNetHandle',
        'description' => 'setDescription',
        'countries' => 'setCountries',
        'geofeed' => 'setGeofeed',
        'latitude' => 'setLatitude',
        'longitude' => 'setLongitude',
        'city' => 'setCity',
        'languages' => 'setLanguages',
        'status' => 'setStatus',
        'organization' => 'setOrganization',
        'sponsoringOrganization' => 'setSponsoringOrganization',
        'remarks' => 'setRemarks',
        'assignmentSize' => 'setAssignmentSize',
        'notify' => 'setNotify',
        'mntBy' => 'setMntBy',
        'mntLower' => 'setMntLower',
        'mntDomains' => 'setMntDomains',
        'mntRoutes' => 'setMntRoutes',
        'mntIrt' => 'setMntIrt',
        'dateCreated' => 'setDateCreated',
        'dateUpdated' => 'setDateUpdated',
        'source' => 'setSource',
        'parents' => 'setParents'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'startIp' => 'getStartIp',
        'endIp' => 'getEndIp',
        'cidr' => 'getCidr',
        'netName' => 'getNetName',
        'netHandle' => 'getNetHandle',
        'description' => 'getDescription',
        'countries' => 'getCountries',
        'geofeed' => 'getGeofeed',
        'latitude' => 'getLatitude',
        'longitude' => 'getLongitude',
        'city' => 'getCity',
        'languages' => 'getLanguages',
        'status' => 'getStatus',
        'organization' => 'getOrganization',
        'sponsoringOrganization' => 'getSponsoringOrganization',
        'remarks' => 'getRemarks',
        'assignmentSize' => 'getAssignmentSize',
        'notify' => 'getNotify',
        'mntBy' => 'getMntBy',
        'mntLower' => 'getMntLower',
        'mntDomains' => 'getMntDomains',
        'mntRoutes' => 'getMntRoutes',
        'mntIrt' => 'getMntIrt',
        'dateCreated' => 'getDateCreated',
        'dateUpdated' => 'getDateUpdated',
        'source' => 'getSource',
        'parents' => 'getParents'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('startIp', $data ?? [], null);
        $this->setIfExists('endIp', $data ?? [], null);
        $this->setIfExists('cidr', $data ?? [], null);
        $this->setIfExists('netName', $data ?? [], null);
        $this->setIfExists('netHandle', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('countries', $data ?? [], null);
        $this->setIfExists('geofeed', $data ?? [], null);
        $this->setIfExists('latitude', $data ?? [], null);
        $this->setIfExists('longitude', $data ?? [], null);
        $this->setIfExists('city', $data ?? [], null);
        $this->setIfExists('languages', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('organization', $data ?? [], null);
        $this->setIfExists('sponsoringOrganization', $data ?? [], null);
        $this->setIfExists('remarks', $data ?? [], null);
        $this->setIfExists('assignmentSize', $data ?? [], null);
        $this->setIfExists('notify', $data ?? [], null);
        $this->setIfExists('mntBy', $data ?? [], null);
        $this->setIfExists('mntLower', $data ?? [], null);
        $this->setIfExists('mntDomains', $data ?? [], null);
        $this->setIfExists('mntRoutes', $data ?? [], null);
        $this->setIfExists('mntIrt', $data ?? [], null);
        $this->setIfExists('dateCreated', $data ?? [], null);
        $this->setIfExists('dateUpdated', $data ?? [], null);
        $this->setIfExists('source', $data ?? [], null);
        $this->setIfExists('parents', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets startIp
     *
     * @return string|null
     */
    public function getStartIp()
    {
        return $this->container['startIp'];
    }

    /**
     * Sets startIp
     *
     * @param string|null $startIp startIp
     *
     * @return self
     */
    public function setStartIp($startIp)
    {
        if (is_null($startIp)) {
            throw new \InvalidArgumentException('non-nullable startIp cannot be null');
        }
        $this->container['startIp'] = $startIp;

        return $this;
    }

    /**
     * Gets endIp
     *
     * @return string|null
     */
    public function getEndIp()
    {
        return $this->container['endIp'];
    }

    /**
     * Sets endIp
     *
     * @param string|null $endIp endIp
     *
     * @return self
     */
    public function setEndIp($endIp)
    {
        if (is_null($endIp)) {
            throw new \InvalidArgumentException('non-nullable endIp cannot be null');
        }
        $this->container['endIp'] = $endIp;

        return $this;
    }

    /**
     * Gets cidr
     *
     * @return string[]|null
     */
    public function getCidr()
    {
        return $this->container['cidr'];
    }

    /**
     * Sets cidr
     *
     * @param string[]|null $cidr cidr
     *
     * @return self
     */
    public function setCidr($cidr)
    {
        if (is_null($cidr)) {
            throw new \InvalidArgumentException('non-nullable cidr cannot be null');
        }
        $this->container['cidr'] = $cidr;

        return $this;
    }

    /**
     * Gets netName
     *
     * @return string|null
     */
    public function getNetName()
    {
        return $this->container['netName'];
    }

    /**
     * Sets netName
     *
     * @param string|null $netName netName
     *
     * @return self
     */
    public function setNetName($netName)
    {
        if (is_null($netName)) {
            throw new \InvalidArgumentException('non-nullable netName cannot be null');
        }
        $this->container['netName'] = $netName;

        return $this;
    }

    /**
     * Gets netHandle
     *
     * @return string|null
     */
    public function getNetHandle()
    {
        return $this->container['netHandle'];
    }

    /**
     * Sets netHandle
     *
     * @param string|null $netHandle netHandle
     *
     * @return self
     */
    public function setNetHandle($netHandle)
    {
        if (is_null($netHandle)) {
            throw new \InvalidArgumentException('non-nullable netHandle cannot be null');
        }
        $this->container['netHandle'] = $netHandle;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string[]|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string[]|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets countries
     *
     * @return string[]|null
     */
    public function getCountries()
    {
        return $this->container['countries'];
    }

    /**
     * Sets countries
     *
     * @param string[]|null $countries countries
     *
     * @return self
     */
    public function setCountries($countries)
    {
        if (is_null($countries)) {
            throw new \InvalidArgumentException('non-nullable countries cannot be null');
        }
        $this->container['countries'] = $countries;

        return $this;
    }

    /**
     * Gets geofeed
     *
     * @return string|null
     */
    public function getGeofeed()
    {
        return $this->container['geofeed'];
    }

    /**
     * Sets geofeed
     *
     * @param string|null $geofeed geofeed
     *
     * @return self
     */
    public function setGeofeed($geofeed)
    {
        if (is_null($geofeed)) {
            throw new \InvalidArgumentException('non-nullable geofeed cannot be null');
        }
        $this->container['geofeed'] = $geofeed;

        return $this;
    }

    /**
     * Gets latitude
     *
     * @return float|null
     */
    public function getLatitude()
    {
        return $this->container['latitude'];
    }

    /**
     * Sets latitude
     *
     * @param float|null $latitude latitude
     *
     * @return self
     */
    public function setLatitude($latitude)
    {
        if (is_null($latitude)) {
            throw new \InvalidArgumentException('non-nullable latitude cannot be null');
        }
        $this->container['latitude'] = $latitude;

        return $this;
    }

    /**
     * Gets longitude
     *
     * @return float|null
     */
    public function getLongitude()
    {
        return $this->container['longitude'];
    }

    /**
     * Sets longitude
     *
     * @param float|null $longitude longitude
     *
     * @return self
     */
    public function setLongitude($longitude)
    {
        if (is_null($longitude)) {
            throw new \InvalidArgumentException('non-nullable longitude cannot be null');
        }
        $this->container['longitude'] = $longitude;

        return $this;
    }

    /**
     * Gets city
     *
     * @return string|null
     */
    public function getCity()
    {
        return $this->container['city'];
    }

    /**
     * Sets city
     *
     * @param string|null $city city
     *
     * @return self
     */
    public function setCity($city)
    {
        if (is_null($city)) {
            throw new \InvalidArgumentException('non-nullable city cannot be null');
        }
        $this->container['city'] = $city;

        return $this;
    }

    /**
     * Gets languages
     *
     * @return string[]|null
     */
    public function getLanguages()
    {
        return $this->container['languages'];
    }

    /**
     * Sets languages
     *
     * @param string[]|null $languages languages
     *
     * @return self
     */
    public function setLanguages($languages)
    {
        if (is_null($languages)) {
            throw new \InvalidArgumentException('non-nullable languages cannot be null');
        }
        $this->container['languages'] = $languages;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets organization
     *
     * @return string|null
     */
    public function getOrganization()
    {
        return $this->container['organization'];
    }

    /**
     * Sets organization
     *
     * @param string|null $organization organization
     *
     * @return self
     */
    public function setOrganization($organization)
    {
        if (is_null($organization)) {
            throw new \InvalidArgumentException('non-nullable organization cannot be null');
        }
        $this->container['organization'] = $organization;

        return $this;
    }

    /**
     * Gets sponsoringOrganization
     *
     * @return string|null
     */
    public function getSponsoringOrganization()
    {
        return $this->container['sponsoringOrganization'];
    }

    /**
     * Sets sponsoringOrganization
     *
     * @param string|null $sponsoringOrganization sponsoringOrganization
     *
     * @return self
     */
    public function setSponsoringOrganization($sponsoringOrganization)
    {
        if (is_null($sponsoringOrganization)) {
            throw new \InvalidArgumentException('non-nullable sponsoringOrganization cannot be null');
        }
        $this->container['sponsoringOrganization'] = $sponsoringOrganization;

        return $this;
    }

    /**
     * Gets remarks
     *
     * @return string[]|null
     */
    public function getRemarks()
    {
        return $this->container['remarks'];
    }

    /**
     * Sets remarks
     *
     * @param string[]|null $remarks remarks
     *
     * @return self
     */
    public function setRemarks($remarks)
    {
        if (is_null($remarks)) {
            throw new \InvalidArgumentException('non-nullable remarks cannot be null');
        }
        $this->container['remarks'] = $remarks;

        return $this;
    }

    /**
     * Gets assignmentSize
     *
     * @return string|null
     */
    public function getAssignmentSize()
    {
        return $this->container['assignmentSize'];
    }

    /**
     * Sets assignmentSize
     *
     * @param string|null $assignmentSize assignmentSize
     *
     * @return self
     */
    public function setAssignmentSize($assignmentSize)
    {
        if (is_null($assignmentSize)) {
            throw new \InvalidArgumentException('non-nullable assignmentSize cannot be null');
        }
        $this->container['assignmentSize'] = $assignmentSize;

        return $this;
    }

    /**
     * Gets notify
     *
     * @return string[]|null
     */
    public function getNotify()
    {
        return $this->container['notify'];
    }

    /**
     * Sets notify
     *
     * @param string[]|null $notify notify
     *
     * @return self
     */
    public function setNotify($notify)
    {
        if (is_null($notify)) {
            throw new \InvalidArgumentException('non-nullable notify cannot be null');
        }
        $this->container['notify'] = $notify;

        return $this;
    }

    /**
     * Gets mntBy
     *
     * @return string[]|null
     */
    public function getMntBy()
    {
        return $this->container['mntBy'];
    }

    /**
     * Sets mntBy
     *
     * @param string[]|null $mntBy mntBy
     *
     * @return self
     */
    public function setMntBy($mntBy)
    {
        if (is_null($mntBy)) {
            throw new \InvalidArgumentException('non-nullable mntBy cannot be null');
        }
        $this->container['mntBy'] = $mntBy;

        return $this;
    }

    /**
     * Gets mntLower
     *
     * @return string[]|null
     */
    public function getMntLower()
    {
        return $this->container['mntLower'];
    }

    /**
     * Sets mntLower
     *
     * @param string[]|null $mntLower mntLower
     *
     * @return self
     */
    public function setMntLower($mntLower)
    {
        if (is_null($mntLower)) {
            throw new \InvalidArgumentException('non-nullable mntLower cannot be null');
        }
        $this->container['mntLower'] = $mntLower;

        return $this;
    }

    /**
     * Gets mntDomains
     *
     * @return string[]|null
     */
    public function getMntDomains()
    {
        return $this->container['mntDomains'];
    }

    /**
     * Sets mntDomains
     *
     * @param string[]|null $mntDomains mntDomains
     *
     * @return self
     */
    public function setMntDomains($mntDomains)
    {
        if (is_null($mntDomains)) {
            throw new \InvalidArgumentException('non-nullable mntDomains cannot be null');
        }
        $this->container['mntDomains'] = $mntDomains;

        return $this;
    }

    /**
     * Gets mntRoutes
     *
     * @return string[]|null
     */
    public function getMntRoutes()
    {
        return $this->container['mntRoutes'];
    }

    /**
     * Sets mntRoutes
     *
     * @param string[]|null $mntRoutes mntRoutes
     *
     * @return self
     */
    public function setMntRoutes($mntRoutes)
    {
        if (is_null($mntRoutes)) {
            throw new \InvalidArgumentException('non-nullable mntRoutes cannot be null');
        }
        $this->container['mntRoutes'] = $mntRoutes;

        return $this;
    }

    /**
     * Gets mntIrt
     *
     * @return string[]|null
     */
    public function getMntIrt()
    {
        return $this->container['mntIrt'];
    }

    /**
     * Sets mntIrt
     *
     * @param string[]|null $mntIrt mntIrt
     *
     * @return self
     */
    public function setMntIrt($mntIrt)
    {
        if (is_null($mntIrt)) {
            throw new \InvalidArgumentException('non-nullable mntIrt cannot be null');
        }
        $this->container['mntIrt'] = $mntIrt;

        return $this;
    }

    /**
     * Gets dateCreated
     *
     * @return string|null
     */
    public function getDateCreated()
    {
        return $this->container['dateCreated'];
    }

    /**
     * Sets dateCreated
     *
     * @param string|null $dateCreated dateCreated
     *
     * @return self
     */
    public function setDateCreated($dateCreated)
    {
        if (is_null($dateCreated)) {
            throw new \InvalidArgumentException('non-nullable dateCreated cannot be null');
        }
        $this->container['dateCreated'] = $dateCreated;

        return $this;
    }

    /**
     * Gets dateUpdated
     *
     * @return string|null
     */
    public function getDateUpdated()
    {
        return $this->container['dateUpdated'];
    }

    /**
     * Sets dateUpdated
     *
     * @param string|null $dateUpdated dateUpdated
     *
     * @return self
     */
    public function setDateUpdated($dateUpdated)
    {
        if (is_null($dateUpdated)) {
            throw new \InvalidArgumentException('non-nullable dateUpdated cannot be null');
        }
        $this->container['dateUpdated'] = $dateUpdated;

        return $this;
    }

    /**
     * Gets source
     *
     * @return string|null
     */
    public function getSource()
    {
        return $this->container['source'];
    }

    /**
     * Sets source
     *
     * @param string|null $source source
     *
     * @return self
     */
    public function setSource($source)
    {
        if (is_null($source)) {
            throw new \InvalidArgumentException('non-nullable source cannot be null');
        }
        $this->container['source'] = $source;

        return $this;
    }

    /**
     * Gets parents
     *
     * @return string[]|null
     */
    public function getParents()
    {
        return $this->container['parents'];
    }

    /**
     * Sets parents
     *
     * @param string[]|null $parents parents
     *
     * @return self
     */
    public function setParents($parents)
    {
        if (is_null($parents)) {
            throw new \InvalidArgumentException('non-nullable parents cannot be null');
        }
        $this->container['parents'] = $parents;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


