<?php
/**
 * Route
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  WhoisFreaks
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * WhoisFreaks API
 *
 * Complete WhoisFreaks API — WHOIS, DNS, SSL, Geolocation, Typosquatting, IP Intelligence, Domain Reputation, and bulk database downloads.  ## Authentication All requests require an `apiKey` query parameter.  ## Resources - Docs: https://whoisfreaks.com/documentation - Billing: https://billing.whoisfreaks.com - Support: support@whoisfreaks.com
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@whoisfreaks.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace WhoisFreaks\Model;

use \ArrayAccess;
use \WhoisFreaks\ObjectSerializer;

/**
 * Route Class Doc Comment
 *
 * @category Class
 * @package  WhoisFreaks
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Route implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Route';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'route' => 'string',
        'description' => 'string[]',
        'origin' => 'string',
        'pingable' => 'string[]',
        'pingHdl' => 'string[]',
        'holes' => 'string[]',
        'country' => 'string',
        'organizations' => 'string[]',
        'memberOf' => 'string[]',
        'inject' => 'string[]',
        'aggrMtd' => 'string',
        'aggrBndry' => 'string',
        'exportComps' => 'string',
        'components' => 'string',
        'remarks' => 'string[]',
        'notify' => 'string[]',
        'mntLower' => 'string[]',
        'mntRoutes' => 'string[]',
        'mntBy' => 'string[]',
        'dateCreated' => 'string',
        'dateUpdated' => 'string',
        'source' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'route' => null,
        'description' => null,
        'origin' => null,
        'pingable' => null,
        'pingHdl' => null,
        'holes' => null,
        'country' => null,
        'organizations' => null,
        'memberOf' => null,
        'inject' => null,
        'aggrMtd' => null,
        'aggrBndry' => null,
        'exportComps' => null,
        'components' => null,
        'remarks' => null,
        'notify' => null,
        'mntLower' => null,
        'mntRoutes' => null,
        'mntBy' => null,
        'dateCreated' => null,
        'dateUpdated' => null,
        'source' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'route' => false,
        'description' => false,
        'origin' => false,
        'pingable' => false,
        'pingHdl' => false,
        'holes' => false,
        'country' => false,
        'organizations' => false,
        'memberOf' => false,
        'inject' => false,
        'aggrMtd' => false,
        'aggrBndry' => false,
        'exportComps' => false,
        'components' => false,
        'remarks' => false,
        'notify' => false,
        'mntLower' => false,
        'mntRoutes' => false,
        'mntBy' => false,
        'dateCreated' => false,
        'dateUpdated' => false,
        'source' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'route' => 'route',
        'description' => 'description',
        'origin' => 'origin',
        'pingable' => 'pingable',
        'pingHdl' => 'ping_hdl',
        'holes' => 'holes',
        'country' => 'country',
        'organizations' => 'organizations',
        'memberOf' => 'member_of',
        'inject' => 'inject',
        'aggrMtd' => 'aggr_mtd',
        'aggrBndry' => 'aggr_bndry',
        'exportComps' => 'export_comps',
        'components' => 'components',
        'remarks' => 'remarks',
        'notify' => 'notify',
        'mntLower' => 'mnt_lower',
        'mntRoutes' => 'mnt_routes',
        'mntBy' => 'mnt_by',
        'dateCreated' => 'date_created',
        'dateUpdated' => 'date_updated',
        'source' => 'source'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'route' => 'setRoute',
        'description' => 'setDescription',
        'origin' => 'setOrigin',
        'pingable' => 'setPingable',
        'pingHdl' => 'setPingHdl',
        'holes' => 'setHoles',
        'country' => 'setCountry',
        'organizations' => 'setOrganizations',
        'memberOf' => 'setMemberOf',
        'inject' => 'setInject',
        'aggrMtd' => 'setAggrMtd',
        'aggrBndry' => 'setAggrBndry',
        'exportComps' => 'setExportComps',
        'components' => 'setComponents',
        'remarks' => 'setRemarks',
        'notify' => 'setNotify',
        'mntLower' => 'setMntLower',
        'mntRoutes' => 'setMntRoutes',
        'mntBy' => 'setMntBy',
        'dateCreated' => 'setDateCreated',
        'dateUpdated' => 'setDateUpdated',
        'source' => 'setSource'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'route' => 'getRoute',
        'description' => 'getDescription',
        'origin' => 'getOrigin',
        'pingable' => 'getPingable',
        'pingHdl' => 'getPingHdl',
        'holes' => 'getHoles',
        'country' => 'getCountry',
        'organizations' => 'getOrganizations',
        'memberOf' => 'getMemberOf',
        'inject' => 'getInject',
        'aggrMtd' => 'getAggrMtd',
        'aggrBndry' => 'getAggrBndry',
        'exportComps' => 'getExportComps',
        'components' => 'getComponents',
        'remarks' => 'getRemarks',
        'notify' => 'getNotify',
        'mntLower' => 'getMntLower',
        'mntRoutes' => 'getMntRoutes',
        'mntBy' => 'getMntBy',
        'dateCreated' => 'getDateCreated',
        'dateUpdated' => 'getDateUpdated',
        'source' => 'getSource'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('route', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('origin', $data ?? [], null);
        $this->setIfExists('pingable', $data ?? [], null);
        $this->setIfExists('pingHdl', $data ?? [], null);
        $this->setIfExists('holes', $data ?? [], null);
        $this->setIfExists('country', $data ?? [], null);
        $this->setIfExists('organizations', $data ?? [], null);
        $this->setIfExists('memberOf', $data ?? [], null);
        $this->setIfExists('inject', $data ?? [], null);
        $this->setIfExists('aggrMtd', $data ?? [], null);
        $this->setIfExists('aggrBndry', $data ?? [], null);
        $this->setIfExists('exportComps', $data ?? [], null);
        $this->setIfExists('components', $data ?? [], null);
        $this->setIfExists('remarks', $data ?? [], null);
        $this->setIfExists('notify', $data ?? [], null);
        $this->setIfExists('mntLower', $data ?? [], null);
        $this->setIfExists('mntRoutes', $data ?? [], null);
        $this->setIfExists('mntBy', $data ?? [], null);
        $this->setIfExists('dateCreated', $data ?? [], null);
        $this->setIfExists('dateUpdated', $data ?? [], null);
        $this->setIfExists('source', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets route
     *
     * @return string|null
     */
    public function getRoute()
    {
        return $this->container['route'];
    }

    /**
     * Sets route
     *
     * @param string|null $route route
     *
     * @return self
     */
    public function setRoute($route)
    {
        if (is_null($route)) {
            throw new \InvalidArgumentException('non-nullable route cannot be null');
        }
        $this->container['route'] = $route;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string[]|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string[]|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets origin
     *
     * @return string|null
     */
    public function getOrigin()
    {
        return $this->container['origin'];
    }

    /**
     * Sets origin
     *
     * @param string|null $origin origin
     *
     * @return self
     */
    public function setOrigin($origin)
    {
        if (is_null($origin)) {
            throw new \InvalidArgumentException('non-nullable origin cannot be null');
        }
        $this->container['origin'] = $origin;

        return $this;
    }

    /**
     * Gets pingable
     *
     * @return string[]|null
     */
    public function getPingable()
    {
        return $this->container['pingable'];
    }

    /**
     * Sets pingable
     *
     * @param string[]|null $pingable pingable
     *
     * @return self
     */
    public function setPingable($pingable)
    {
        if (is_null($pingable)) {
            throw new \InvalidArgumentException('non-nullable pingable cannot be null');
        }
        $this->container['pingable'] = $pingable;

        return $this;
    }

    /**
     * Gets pingHdl
     *
     * @return string[]|null
     */
    public function getPingHdl()
    {
        return $this->container['pingHdl'];
    }

    /**
     * Sets pingHdl
     *
     * @param string[]|null $pingHdl pingHdl
     *
     * @return self
     */
    public function setPingHdl($pingHdl)
    {
        if (is_null($pingHdl)) {
            throw new \InvalidArgumentException('non-nullable pingHdl cannot be null');
        }
        $this->container['pingHdl'] = $pingHdl;

        return $this;
    }

    /**
     * Gets holes
     *
     * @return string[]|null
     */
    public function getHoles()
    {
        return $this->container['holes'];
    }

    /**
     * Sets holes
     *
     * @param string[]|null $holes holes
     *
     * @return self
     */
    public function setHoles($holes)
    {
        if (is_null($holes)) {
            throw new \InvalidArgumentException('non-nullable holes cannot be null');
        }
        $this->container['holes'] = $holes;

        return $this;
    }

    /**
     * Gets country
     *
     * @return string|null
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param string|null $country country
     *
     * @return self
     */
    public function setCountry($country)
    {
        if (is_null($country)) {
            throw new \InvalidArgumentException('non-nullable country cannot be null');
        }
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets organizations
     *
     * @return string[]|null
     */
    public function getOrganizations()
    {
        return $this->container['organizations'];
    }

    /**
     * Sets organizations
     *
     * @param string[]|null $organizations organizations
     *
     * @return self
     */
    public function setOrganizations($organizations)
    {
        if (is_null($organizations)) {
            throw new \InvalidArgumentException('non-nullable organizations cannot be null');
        }
        $this->container['organizations'] = $organizations;

        return $this;
    }

    /**
     * Gets memberOf
     *
     * @return string[]|null
     */
    public function getMemberOf()
    {
        return $this->container['memberOf'];
    }

    /**
     * Sets memberOf
     *
     * @param string[]|null $memberOf memberOf
     *
     * @return self
     */
    public function setMemberOf($memberOf)
    {
        if (is_null($memberOf)) {
            throw new \InvalidArgumentException('non-nullable memberOf cannot be null');
        }
        $this->container['memberOf'] = $memberOf;

        return $this;
    }

    /**
     * Gets inject
     *
     * @return string[]|null
     */
    public function getInject()
    {
        return $this->container['inject'];
    }

    /**
     * Sets inject
     *
     * @param string[]|null $inject inject
     *
     * @return self
     */
    public function setInject($inject)
    {
        if (is_null($inject)) {
            throw new \InvalidArgumentException('non-nullable inject cannot be null');
        }
        $this->container['inject'] = $inject;

        return $this;
    }

    /**
     * Gets aggrMtd
     *
     * @return string|null
     */
    public function getAggrMtd()
    {
        return $this->container['aggrMtd'];
    }

    /**
     * Sets aggrMtd
     *
     * @param string|null $aggrMtd aggrMtd
     *
     * @return self
     */
    public function setAggrMtd($aggrMtd)
    {
        if (is_null($aggrMtd)) {
            throw new \InvalidArgumentException('non-nullable aggrMtd cannot be null');
        }
        $this->container['aggrMtd'] = $aggrMtd;

        return $this;
    }

    /**
     * Gets aggrBndry
     *
     * @return string|null
     */
    public function getAggrBndry()
    {
        return $this->container['aggrBndry'];
    }

    /**
     * Sets aggrBndry
     *
     * @param string|null $aggrBndry aggrBndry
     *
     * @return self
     */
    public function setAggrBndry($aggrBndry)
    {
        if (is_null($aggrBndry)) {
            throw new \InvalidArgumentException('non-nullable aggrBndry cannot be null');
        }
        $this->container['aggrBndry'] = $aggrBndry;

        return $this;
    }

    /**
     * Gets exportComps
     *
     * @return string|null
     */
    public function getExportComps()
    {
        return $this->container['exportComps'];
    }

    /**
     * Sets exportComps
     *
     * @param string|null $exportComps exportComps
     *
     * @return self
     */
    public function setExportComps($exportComps)
    {
        if (is_null($exportComps)) {
            throw new \InvalidArgumentException('non-nullable exportComps cannot be null');
        }
        $this->container['exportComps'] = $exportComps;

        return $this;
    }

    /**
     * Gets components
     *
     * @return string|null
     */
    public function getComponents()
    {
        return $this->container['components'];
    }

    /**
     * Sets components
     *
     * @param string|null $components components
     *
     * @return self
     */
    public function setComponents($components)
    {
        if (is_null($components)) {
            throw new \InvalidArgumentException('non-nullable components cannot be null');
        }
        $this->container['components'] = $components;

        return $this;
    }

    /**
     * Gets remarks
     *
     * @return string[]|null
     */
    public function getRemarks()
    {
        return $this->container['remarks'];
    }

    /**
     * Sets remarks
     *
     * @param string[]|null $remarks remarks
     *
     * @return self
     */
    public function setRemarks($remarks)
    {
        if (is_null($remarks)) {
            throw new \InvalidArgumentException('non-nullable remarks cannot be null');
        }
        $this->container['remarks'] = $remarks;

        return $this;
    }

    /**
     * Gets notify
     *
     * @return string[]|null
     */
    public function getNotify()
    {
        return $this->container['notify'];
    }

    /**
     * Sets notify
     *
     * @param string[]|null $notify notify
     *
     * @return self
     */
    public function setNotify($notify)
    {
        if (is_null($notify)) {
            throw new \InvalidArgumentException('non-nullable notify cannot be null');
        }
        $this->container['notify'] = $notify;

        return $this;
    }

    /**
     * Gets mntLower
     *
     * @return string[]|null
     */
    public function getMntLower()
    {
        return $this->container['mntLower'];
    }

    /**
     * Sets mntLower
     *
     * @param string[]|null $mntLower mntLower
     *
     * @return self
     */
    public function setMntLower($mntLower)
    {
        if (is_null($mntLower)) {
            throw new \InvalidArgumentException('non-nullable mntLower cannot be null');
        }
        $this->container['mntLower'] = $mntLower;

        return $this;
    }

    /**
     * Gets mntRoutes
     *
     * @return string[]|null
     */
    public function getMntRoutes()
    {
        return $this->container['mntRoutes'];
    }

    /**
     * Sets mntRoutes
     *
     * @param string[]|null $mntRoutes mntRoutes
     *
     * @return self
     */
    public function setMntRoutes($mntRoutes)
    {
        if (is_null($mntRoutes)) {
            throw new \InvalidArgumentException('non-nullable mntRoutes cannot be null');
        }
        $this->container['mntRoutes'] = $mntRoutes;

        return $this;
    }

    /**
     * Gets mntBy
     *
     * @return string[]|null
     */
    public function getMntBy()
    {
        return $this->container['mntBy'];
    }

    /**
     * Sets mntBy
     *
     * @param string[]|null $mntBy mntBy
     *
     * @return self
     */
    public function setMntBy($mntBy)
    {
        if (is_null($mntBy)) {
            throw new \InvalidArgumentException('non-nullable mntBy cannot be null');
        }
        $this->container['mntBy'] = $mntBy;

        return $this;
    }

    /**
     * Gets dateCreated
     *
     * @return string|null
     */
    public function getDateCreated()
    {
        return $this->container['dateCreated'];
    }

    /**
     * Sets dateCreated
     *
     * @param string|null $dateCreated dateCreated
     *
     * @return self
     */
    public function setDateCreated($dateCreated)
    {
        if (is_null($dateCreated)) {
            throw new \InvalidArgumentException('non-nullable dateCreated cannot be null');
        }
        $this->container['dateCreated'] = $dateCreated;

        return $this;
    }

    /**
     * Gets dateUpdated
     *
     * @return string|null
     */
    public function getDateUpdated()
    {
        return $this->container['dateUpdated'];
    }

    /**
     * Sets dateUpdated
     *
     * @param string|null $dateUpdated dateUpdated
     *
     * @return self
     */
    public function setDateUpdated($dateUpdated)
    {
        if (is_null($dateUpdated)) {
            throw new \InvalidArgumentException('non-nullable dateUpdated cannot be null');
        }
        $this->container['dateUpdated'] = $dateUpdated;

        return $this;
    }

    /**
     * Gets source
     *
     * @return string|null
     */
    public function getSource()
    {
        return $this->container['source'];
    }

    /**
     * Sets source
     *
     * @param string|null $source source
     *
     * @return self
     */
    public function setSource($source)
    {
        if (is_null($source)) {
            throw new \InvalidArgumentException('non-nullable source cannot be null');
        }
        $this->container['source'] = $source;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


