<?php
/**
 * SslExtensionsInfo
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  WhoisFreaks
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * WhoisFreaks API
 *
 * Complete WhoisFreaks API — WHOIS, DNS, SSL, Geolocation, Typosquatting, IP Intelligence, Domain Reputation, and bulk database downloads.  ## Authentication All requests require an `apiKey` query parameter.  ## Resources - Docs: https://whoisfreaks.com/documentation - Billing: https://billing.whoisfreaks.com - Support: support@whoisfreaks.com
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@whoisfreaks.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace WhoisFreaks\Model;

use \ArrayAccess;
use \WhoisFreaks\ObjectSerializer;

/**
 * SslExtensionsInfo Class Doc Comment
 *
 * @category Class
 * @package  WhoisFreaks
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SslExtensionsInfo implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SslExtensionsInfo';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'authorityKeyIdentifier' => 'string',
        'subjectKeyIdentifier' => 'string',
        'keyUsages' => 'string[]',
        'extendedKeyUsages' => 'string[]',
        'crlDistributionPoints' => 'string[]',
        'authorityInfoAccess' => '\WhoisFreaks\Model\SslAuthorityInfo',
        'subjectAlternativeNames' => '\WhoisFreaks\Model\SslAlternateNames',
        'certificatePolicies' => '\WhoisFreaks\Model\SslCertificatePolicy[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'authorityKeyIdentifier' => null,
        'subjectKeyIdentifier' => null,
        'keyUsages' => null,
        'extendedKeyUsages' => null,
        'crlDistributionPoints' => null,
        'authorityInfoAccess' => null,
        'subjectAlternativeNames' => null,
        'certificatePolicies' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'authorityKeyIdentifier' => false,
        'subjectKeyIdentifier' => false,
        'keyUsages' => false,
        'extendedKeyUsages' => false,
        'crlDistributionPoints' => false,
        'authorityInfoAccess' => false,
        'subjectAlternativeNames' => false,
        'certificatePolicies' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'authorityKeyIdentifier' => 'authorityKeyIdentifier',
        'subjectKeyIdentifier' => 'subjectKeyIdentifier',
        'keyUsages' => 'keyUsages',
        'extendedKeyUsages' => 'extendedKeyUsages',
        'crlDistributionPoints' => 'crlDistributionPoints',
        'authorityInfoAccess' => 'authorityInfoAccess',
        'subjectAlternativeNames' => 'subjectAlternativeNames',
        'certificatePolicies' => 'certificatePolicies'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'authorityKeyIdentifier' => 'setAuthorityKeyIdentifier',
        'subjectKeyIdentifier' => 'setSubjectKeyIdentifier',
        'keyUsages' => 'setKeyUsages',
        'extendedKeyUsages' => 'setExtendedKeyUsages',
        'crlDistributionPoints' => 'setCrlDistributionPoints',
        'authorityInfoAccess' => 'setAuthorityInfoAccess',
        'subjectAlternativeNames' => 'setSubjectAlternativeNames',
        'certificatePolicies' => 'setCertificatePolicies'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'authorityKeyIdentifier' => 'getAuthorityKeyIdentifier',
        'subjectKeyIdentifier' => 'getSubjectKeyIdentifier',
        'keyUsages' => 'getKeyUsages',
        'extendedKeyUsages' => 'getExtendedKeyUsages',
        'crlDistributionPoints' => 'getCrlDistributionPoints',
        'authorityInfoAccess' => 'getAuthorityInfoAccess',
        'subjectAlternativeNames' => 'getSubjectAlternativeNames',
        'certificatePolicies' => 'getCertificatePolicies'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('authorityKeyIdentifier', $data ?? [], null);
        $this->setIfExists('subjectKeyIdentifier', $data ?? [], null);
        $this->setIfExists('keyUsages', $data ?? [], null);
        $this->setIfExists('extendedKeyUsages', $data ?? [], null);
        $this->setIfExists('crlDistributionPoints', $data ?? [], null);
        $this->setIfExists('authorityInfoAccess', $data ?? [], null);
        $this->setIfExists('subjectAlternativeNames', $data ?? [], null);
        $this->setIfExists('certificatePolicies', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets authorityKeyIdentifier
     *
     * @return string|null
     */
    public function getAuthorityKeyIdentifier()
    {
        return $this->container['authorityKeyIdentifier'];
    }

    /**
     * Sets authorityKeyIdentifier
     *
     * @param string|null $authorityKeyIdentifier authorityKeyIdentifier
     *
     * @return self
     */
    public function setAuthorityKeyIdentifier($authorityKeyIdentifier)
    {
        if (is_null($authorityKeyIdentifier)) {
            throw new \InvalidArgumentException('non-nullable authorityKeyIdentifier cannot be null');
        }
        $this->container['authorityKeyIdentifier'] = $authorityKeyIdentifier;

        return $this;
    }

    /**
     * Gets subjectKeyIdentifier
     *
     * @return string|null
     */
    public function getSubjectKeyIdentifier()
    {
        return $this->container['subjectKeyIdentifier'];
    }

    /**
     * Sets subjectKeyIdentifier
     *
     * @param string|null $subjectKeyIdentifier subjectKeyIdentifier
     *
     * @return self
     */
    public function setSubjectKeyIdentifier($subjectKeyIdentifier)
    {
        if (is_null($subjectKeyIdentifier)) {
            throw new \InvalidArgumentException('non-nullable subjectKeyIdentifier cannot be null');
        }
        $this->container['subjectKeyIdentifier'] = $subjectKeyIdentifier;

        return $this;
    }

    /**
     * Gets keyUsages
     *
     * @return string[]|null
     */
    public function getKeyUsages()
    {
        return $this->container['keyUsages'];
    }

    /**
     * Sets keyUsages
     *
     * @param string[]|null $keyUsages keyUsages
     *
     * @return self
     */
    public function setKeyUsages($keyUsages)
    {
        if (is_null($keyUsages)) {
            throw new \InvalidArgumentException('non-nullable keyUsages cannot be null');
        }
        $this->container['keyUsages'] = $keyUsages;

        return $this;
    }

    /**
     * Gets extendedKeyUsages
     *
     * @return string[]|null
     */
    public function getExtendedKeyUsages()
    {
        return $this->container['extendedKeyUsages'];
    }

    /**
     * Sets extendedKeyUsages
     *
     * @param string[]|null $extendedKeyUsages extendedKeyUsages
     *
     * @return self
     */
    public function setExtendedKeyUsages($extendedKeyUsages)
    {
        if (is_null($extendedKeyUsages)) {
            throw new \InvalidArgumentException('non-nullable extendedKeyUsages cannot be null');
        }
        $this->container['extendedKeyUsages'] = $extendedKeyUsages;

        return $this;
    }

    /**
     * Gets crlDistributionPoints
     *
     * @return string[]|null
     */
    public function getCrlDistributionPoints()
    {
        return $this->container['crlDistributionPoints'];
    }

    /**
     * Sets crlDistributionPoints
     *
     * @param string[]|null $crlDistributionPoints crlDistributionPoints
     *
     * @return self
     */
    public function setCrlDistributionPoints($crlDistributionPoints)
    {
        if (is_null($crlDistributionPoints)) {
            throw new \InvalidArgumentException('non-nullable crlDistributionPoints cannot be null');
        }
        $this->container['crlDistributionPoints'] = $crlDistributionPoints;

        return $this;
    }

    /**
     * Gets authorityInfoAccess
     *
     * @return \WhoisFreaks\Model\SslAuthorityInfo|null
     */
    public function getAuthorityInfoAccess()
    {
        return $this->container['authorityInfoAccess'];
    }

    /**
     * Sets authorityInfoAccess
     *
     * @param \WhoisFreaks\Model\SslAuthorityInfo|null $authorityInfoAccess authorityInfoAccess
     *
     * @return self
     */
    public function setAuthorityInfoAccess($authorityInfoAccess)
    {
        if (is_null($authorityInfoAccess)) {
            throw new \InvalidArgumentException('non-nullable authorityInfoAccess cannot be null');
        }
        $this->container['authorityInfoAccess'] = $authorityInfoAccess;

        return $this;
    }

    /**
     * Gets subjectAlternativeNames
     *
     * @return \WhoisFreaks\Model\SslAlternateNames|null
     */
    public function getSubjectAlternativeNames()
    {
        return $this->container['subjectAlternativeNames'];
    }

    /**
     * Sets subjectAlternativeNames
     *
     * @param \WhoisFreaks\Model\SslAlternateNames|null $subjectAlternativeNames subjectAlternativeNames
     *
     * @return self
     */
    public function setSubjectAlternativeNames($subjectAlternativeNames)
    {
        if (is_null($subjectAlternativeNames)) {
            throw new \InvalidArgumentException('non-nullable subjectAlternativeNames cannot be null');
        }
        $this->container['subjectAlternativeNames'] = $subjectAlternativeNames;

        return $this;
    }

    /**
     * Gets certificatePolicies
     *
     * @return \WhoisFreaks\Model\SslCertificatePolicy[]|null
     */
    public function getCertificatePolicies()
    {
        return $this->container['certificatePolicies'];
    }

    /**
     * Sets certificatePolicies
     *
     * @param \WhoisFreaks\Model\SslCertificatePolicy[]|null $certificatePolicies certificatePolicies
     *
     * @return self
     */
    public function setCertificatePolicies($certificatePolicies)
    {
        if (is_null($certificatePolicies)) {
            throw new \InvalidArgumentException('non-nullable certificatePolicies cannot be null');
        }
        $this->container['certificatePolicies'] = $certificatePolicies;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


