<?php
/**
 * WhoisPerson
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  WhoisFreaks
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * WhoisFreaks API
 *
 * Complete WhoisFreaks API — WHOIS, DNS, SSL, Geolocation, Typosquatting, IP Intelligence, Domain Reputation, and bulk database downloads.  ## Authentication All requests require an `apiKey` query parameter.  ## Resources - Docs: https://whoisfreaks.com/documentation - Billing: https://billing.whoisfreaks.com - Support: support@whoisfreaks.com
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@whoisfreaks.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace WhoisFreaks\Model;

use \ArrayAccess;
use \WhoisFreaks\ObjectSerializer;

/**
 * WhoisPerson Class Doc Comment
 *
 * @category Class
 * @package  WhoisFreaks
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class WhoisPerson implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'WhoisPerson';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'handle' => 'string',
        'name' => 'string',
        'address' => 'string[]',
        'street' => 'string',
        'city' => 'string',
        'district' => 'string',
        'state' => 'string',
        'zipCode' => 'string',
        'country' => 'string',
        'email' => 'string[]',
        'abuseMailbox' => 'string[]',
        'phone' => 'string[]',
        'faxNo' => 'string[]',
        'organizations' => 'string[]',
        'adminContacts' => 'string[]',
        'techContacts' => 'string[]',
        'remarks' => 'string[]',
        'notify' => 'string[]',
        'mntBy' => 'string[]',
        'mntRef' => 'string[]',
        'dateCreated' => 'string',
        'dateUpdated' => 'string',
        'source' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'handle' => null,
        'name' => null,
        'address' => null,
        'street' => null,
        'city' => null,
        'district' => null,
        'state' => null,
        'zipCode' => null,
        'country' => null,
        'email' => null,
        'abuseMailbox' => null,
        'phone' => null,
        'faxNo' => null,
        'organizations' => null,
        'adminContacts' => null,
        'techContacts' => null,
        'remarks' => null,
        'notify' => null,
        'mntBy' => null,
        'mntRef' => null,
        'dateCreated' => null,
        'dateUpdated' => null,
        'source' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'handle' => false,
        'name' => false,
        'address' => false,
        'street' => false,
        'city' => false,
        'district' => false,
        'state' => false,
        'zipCode' => false,
        'country' => false,
        'email' => false,
        'abuseMailbox' => false,
        'phone' => false,
        'faxNo' => false,
        'organizations' => false,
        'adminContacts' => false,
        'techContacts' => false,
        'remarks' => false,
        'notify' => false,
        'mntBy' => false,
        'mntRef' => false,
        'dateCreated' => false,
        'dateUpdated' => false,
        'source' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'handle' => 'handle',
        'name' => 'name',
        'address' => 'address',
        'street' => 'street',
        'city' => 'city',
        'district' => 'district',
        'state' => 'state',
        'zipCode' => 'zip_code',
        'country' => 'country',
        'email' => 'email',
        'abuseMailbox' => 'abuse_mailbox',
        'phone' => 'phone',
        'faxNo' => 'fax_no',
        'organizations' => 'organizations',
        'adminContacts' => 'admin_contacts',
        'techContacts' => 'tech_contacts',
        'remarks' => 'remarks',
        'notify' => 'notify',
        'mntBy' => 'mnt_by',
        'mntRef' => 'mnt_ref',
        'dateCreated' => 'date_created',
        'dateUpdated' => 'date_updated',
        'source' => 'source'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'handle' => 'setHandle',
        'name' => 'setName',
        'address' => 'setAddress',
        'street' => 'setStreet',
        'city' => 'setCity',
        'district' => 'setDistrict',
        'state' => 'setState',
        'zipCode' => 'setZipCode',
        'country' => 'setCountry',
        'email' => 'setEmail',
        'abuseMailbox' => 'setAbuseMailbox',
        'phone' => 'setPhone',
        'faxNo' => 'setFaxNo',
        'organizations' => 'setOrganizations',
        'adminContacts' => 'setAdminContacts',
        'techContacts' => 'setTechContacts',
        'remarks' => 'setRemarks',
        'notify' => 'setNotify',
        'mntBy' => 'setMntBy',
        'mntRef' => 'setMntRef',
        'dateCreated' => 'setDateCreated',
        'dateUpdated' => 'setDateUpdated',
        'source' => 'setSource'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'handle' => 'getHandle',
        'name' => 'getName',
        'address' => 'getAddress',
        'street' => 'getStreet',
        'city' => 'getCity',
        'district' => 'getDistrict',
        'state' => 'getState',
        'zipCode' => 'getZipCode',
        'country' => 'getCountry',
        'email' => 'getEmail',
        'abuseMailbox' => 'getAbuseMailbox',
        'phone' => 'getPhone',
        'faxNo' => 'getFaxNo',
        'organizations' => 'getOrganizations',
        'adminContacts' => 'getAdminContacts',
        'techContacts' => 'getTechContacts',
        'remarks' => 'getRemarks',
        'notify' => 'getNotify',
        'mntBy' => 'getMntBy',
        'mntRef' => 'getMntRef',
        'dateCreated' => 'getDateCreated',
        'dateUpdated' => 'getDateUpdated',
        'source' => 'getSource'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('handle', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('address', $data ?? [], null);
        $this->setIfExists('street', $data ?? [], null);
        $this->setIfExists('city', $data ?? [], null);
        $this->setIfExists('district', $data ?? [], null);
        $this->setIfExists('state', $data ?? [], null);
        $this->setIfExists('zipCode', $data ?? [], null);
        $this->setIfExists('country', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('abuseMailbox', $data ?? [], null);
        $this->setIfExists('phone', $data ?? [], null);
        $this->setIfExists('faxNo', $data ?? [], null);
        $this->setIfExists('organizations', $data ?? [], null);
        $this->setIfExists('adminContacts', $data ?? [], null);
        $this->setIfExists('techContacts', $data ?? [], null);
        $this->setIfExists('remarks', $data ?? [], null);
        $this->setIfExists('notify', $data ?? [], null);
        $this->setIfExists('mntBy', $data ?? [], null);
        $this->setIfExists('mntRef', $data ?? [], null);
        $this->setIfExists('dateCreated', $data ?? [], null);
        $this->setIfExists('dateUpdated', $data ?? [], null);
        $this->setIfExists('source', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets handle
     *
     * @return string|null
     */
    public function getHandle()
    {
        return $this->container['handle'];
    }

    /**
     * Sets handle
     *
     * @param string|null $handle handle
     *
     * @return self
     */
    public function setHandle($handle)
    {
        if (is_null($handle)) {
            throw new \InvalidArgumentException('non-nullable handle cannot be null');
        }
        $this->container['handle'] = $handle;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets address
     *
     * @return string[]|null
     */
    public function getAddress()
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param string[]|null $address address
     *
     * @return self
     */
    public function setAddress($address)
    {
        if (is_null($address)) {
            throw new \InvalidArgumentException('non-nullable address cannot be null');
        }
        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets street
     *
     * @return string|null
     */
    public function getStreet()
    {
        return $this->container['street'];
    }

    /**
     * Sets street
     *
     * @param string|null $street street
     *
     * @return self
     */
    public function setStreet($street)
    {
        if (is_null($street)) {
            throw new \InvalidArgumentException('non-nullable street cannot be null');
        }
        $this->container['street'] = $street;

        return $this;
    }

    /**
     * Gets city
     *
     * @return string|null
     */
    public function getCity()
    {
        return $this->container['city'];
    }

    /**
     * Sets city
     *
     * @param string|null $city city
     *
     * @return self
     */
    public function setCity($city)
    {
        if (is_null($city)) {
            throw new \InvalidArgumentException('non-nullable city cannot be null');
        }
        $this->container['city'] = $city;

        return $this;
    }

    /**
     * Gets district
     *
     * @return string|null
     */
    public function getDistrict()
    {
        return $this->container['district'];
    }

    /**
     * Sets district
     *
     * @param string|null $district district
     *
     * @return self
     */
    public function setDistrict($district)
    {
        if (is_null($district)) {
            throw new \InvalidArgumentException('non-nullable district cannot be null');
        }
        $this->container['district'] = $district;

        return $this;
    }

    /**
     * Gets state
     *
     * @return string|null
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param string|null $state state
     *
     * @return self
     */
    public function setState($state)
    {
        if (is_null($state)) {
            throw new \InvalidArgumentException('non-nullable state cannot be null');
        }
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets zipCode
     *
     * @return string|null
     */
    public function getZipCode()
    {
        return $this->container['zipCode'];
    }

    /**
     * Sets zipCode
     *
     * @param string|null $zipCode zipCode
     *
     * @return self
     */
    public function setZipCode($zipCode)
    {
        if (is_null($zipCode)) {
            throw new \InvalidArgumentException('non-nullable zipCode cannot be null');
        }
        $this->container['zipCode'] = $zipCode;

        return $this;
    }

    /**
     * Gets country
     *
     * @return string|null
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param string|null $country country
     *
     * @return self
     */
    public function setCountry($country)
    {
        if (is_null($country)) {
            throw new \InvalidArgumentException('non-nullable country cannot be null');
        }
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string[]|null
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string[]|null $email email
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            throw new \InvalidArgumentException('non-nullable email cannot be null');
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets abuseMailbox
     *
     * @return string[]|null
     */
    public function getAbuseMailbox()
    {
        return $this->container['abuseMailbox'];
    }

    /**
     * Sets abuseMailbox
     *
     * @param string[]|null $abuseMailbox abuseMailbox
     *
     * @return self
     */
    public function setAbuseMailbox($abuseMailbox)
    {
        if (is_null($abuseMailbox)) {
            throw new \InvalidArgumentException('non-nullable abuseMailbox cannot be null');
        }
        $this->container['abuseMailbox'] = $abuseMailbox;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return string[]|null
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param string[]|null $phone phone
     *
     * @return self
     */
    public function setPhone($phone)
    {
        if (is_null($phone)) {
            throw new \InvalidArgumentException('non-nullable phone cannot be null');
        }
        $this->container['phone'] = $phone;

        return $this;
    }

    /**
     * Gets faxNo
     *
     * @return string[]|null
     */
    public function getFaxNo()
    {
        return $this->container['faxNo'];
    }

    /**
     * Sets faxNo
     *
     * @param string[]|null $faxNo faxNo
     *
     * @return self
     */
    public function setFaxNo($faxNo)
    {
        if (is_null($faxNo)) {
            throw new \InvalidArgumentException('non-nullable faxNo cannot be null');
        }
        $this->container['faxNo'] = $faxNo;

        return $this;
    }

    /**
     * Gets organizations
     *
     * @return string[]|null
     */
    public function getOrganizations()
    {
        return $this->container['organizations'];
    }

    /**
     * Sets organizations
     *
     * @param string[]|null $organizations organizations
     *
     * @return self
     */
    public function setOrganizations($organizations)
    {
        if (is_null($organizations)) {
            throw new \InvalidArgumentException('non-nullable organizations cannot be null');
        }
        $this->container['organizations'] = $organizations;

        return $this;
    }

    /**
     * Gets adminContacts
     *
     * @return string[]|null
     */
    public function getAdminContacts()
    {
        return $this->container['adminContacts'];
    }

    /**
     * Sets adminContacts
     *
     * @param string[]|null $adminContacts adminContacts
     *
     * @return self
     */
    public function setAdminContacts($adminContacts)
    {
        if (is_null($adminContacts)) {
            throw new \InvalidArgumentException('non-nullable adminContacts cannot be null');
        }
        $this->container['adminContacts'] = $adminContacts;

        return $this;
    }

    /**
     * Gets techContacts
     *
     * @return string[]|null
     */
    public function getTechContacts()
    {
        return $this->container['techContacts'];
    }

    /**
     * Sets techContacts
     *
     * @param string[]|null $techContacts techContacts
     *
     * @return self
     */
    public function setTechContacts($techContacts)
    {
        if (is_null($techContacts)) {
            throw new \InvalidArgumentException('non-nullable techContacts cannot be null');
        }
        $this->container['techContacts'] = $techContacts;

        return $this;
    }

    /**
     * Gets remarks
     *
     * @return string[]|null
     */
    public function getRemarks()
    {
        return $this->container['remarks'];
    }

    /**
     * Sets remarks
     *
     * @param string[]|null $remarks remarks
     *
     * @return self
     */
    public function setRemarks($remarks)
    {
        if (is_null($remarks)) {
            throw new \InvalidArgumentException('non-nullable remarks cannot be null');
        }
        $this->container['remarks'] = $remarks;

        return $this;
    }

    /**
     * Gets notify
     *
     * @return string[]|null
     */
    public function getNotify()
    {
        return $this->container['notify'];
    }

    /**
     * Sets notify
     *
     * @param string[]|null $notify notify
     *
     * @return self
     */
    public function setNotify($notify)
    {
        if (is_null($notify)) {
            throw new \InvalidArgumentException('non-nullable notify cannot be null');
        }
        $this->container['notify'] = $notify;

        return $this;
    }

    /**
     * Gets mntBy
     *
     * @return string[]|null
     */
    public function getMntBy()
    {
        return $this->container['mntBy'];
    }

    /**
     * Sets mntBy
     *
     * @param string[]|null $mntBy mntBy
     *
     * @return self
     */
    public function setMntBy($mntBy)
    {
        if (is_null($mntBy)) {
            throw new \InvalidArgumentException('non-nullable mntBy cannot be null');
        }
        $this->container['mntBy'] = $mntBy;

        return $this;
    }

    /**
     * Gets mntRef
     *
     * @return string[]|null
     */
    public function getMntRef()
    {
        return $this->container['mntRef'];
    }

    /**
     * Sets mntRef
     *
     * @param string[]|null $mntRef mntRef
     *
     * @return self
     */
    public function setMntRef($mntRef)
    {
        if (is_null($mntRef)) {
            throw new \InvalidArgumentException('non-nullable mntRef cannot be null');
        }
        $this->container['mntRef'] = $mntRef;

        return $this;
    }

    /**
     * Gets dateCreated
     *
     * @return string|null
     */
    public function getDateCreated()
    {
        return $this->container['dateCreated'];
    }

    /**
     * Sets dateCreated
     *
     * @param string|null $dateCreated dateCreated
     *
     * @return self
     */
    public function setDateCreated($dateCreated)
    {
        if (is_null($dateCreated)) {
            throw new \InvalidArgumentException('non-nullable dateCreated cannot be null');
        }
        $this->container['dateCreated'] = $dateCreated;

        return $this;
    }

    /**
     * Gets dateUpdated
     *
     * @return string|null
     */
    public function getDateUpdated()
    {
        return $this->container['dateUpdated'];
    }

    /**
     * Sets dateUpdated
     *
     * @param string|null $dateUpdated dateUpdated
     *
     * @return self
     */
    public function setDateUpdated($dateUpdated)
    {
        if (is_null($dateUpdated)) {
            throw new \InvalidArgumentException('non-nullable dateUpdated cannot be null');
        }
        $this->container['dateUpdated'] = $dateUpdated;

        return $this;
    }

    /**
     * Gets source
     *
     * @return string|null
     */
    public function getSource()
    {
        return $this->container['source'];
    }

    /**
     * Sets source
     *
     * @param string|null $source source
     *
     * @return self
     */
    public function setSource($source)
    {
        if (is_null($source)) {
            throw new \InvalidArgumentException('non-nullable source cannot be null');
        }
        $this->container['source'] = $source;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


