<?php
/**
 * ReputationIndicatorsTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  WhoisFreaks
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * WhoisFreaks API
 *
 * Complete WhoisFreaks API — WHOIS, DNS, SSL, Geolocation, Typosquatting, IP Intelligence, Domain Reputation, and bulk database downloads.  ## Authentication All requests require an `apiKey` query parameter.  ## Resources - Docs: https://whoisfreaks.com/documentation - Billing: https://billing.whoisfreaks.com - Support: support@whoisfreaks.com
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@whoisfreaks.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace WhoisFreaks\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ReputationIndicatorsTest Class Doc Comment
 *
 * @category    Class
 * @description ReputationIndicators
 * @package     WhoisFreaks
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ReputationIndicatorsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ReputationIndicators"
     */
    public function testReputationIndicators()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "isNewlyRegistered"
     */
    public function testPropertyIsNewlyRegistered()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "usesFreeExtension"
     */
    public function testPropertyUsesFreeExtension()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "usesFreeSsl"
     */
    public function testPropertyUsesFreeSsl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "hasPrivacyWhois"
     */
    public function testPropertyHasPrivacyWhois()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sslAgeDays"
     */
    public function testPropertySslAgeDays()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "hasDmarc"
     */
    public function testPropertyHasDmarc()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "hasSpf"
     */
    public function testPropertyHasSpf()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "redirectsExternally"
     */
    public function testPropertyRedirectsExternally()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "javascriptObfuscated"
     */
    public function testPropertyJavascriptObfuscated()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "domainAgeDays"
     */
    public function testPropertyDomainAgeDays()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "registrar"
     */
    public function testPropertyRegistrar()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
