<?php
/**
 * ResellerContactTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  WhoisFreaks
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * WhoisFreaks API
 *
 * Complete WhoisFreaks API — WHOIS, DNS, SSL, Geolocation, Typosquatting, IP Intelligence, Domain Reputation, and bulk database downloads.  ## Authentication All requests require an `apiKey` query parameter.  ## Resources - Docs: https://whoisfreaks.com/documentation - Billing: https://billing.whoisfreaks.com - Support: support@whoisfreaks.com
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@whoisfreaks.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace WhoisFreaks\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ResellerContactTest Class Doc Comment
 *
 * @category    Class
 * @description ResellerContact
 * @package     WhoisFreaks
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ResellerContactTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ResellerContact"
     */
    public function testResellerContact()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "emailAddress"
     */
    public function testPropertyEmailAddress()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
